"use strict";
require("dotenv").config();
const path=require("path");
const express=require("express");
const session=require("express-session");
const pgSession=require("connect-pg-simple")(session);
const bcrypt=require("bcryptjs");
const helmet=require("helmet");
const compression=require("compression");
const {Client,GatewayIntentBits}=require("discord.js");
const {Pool}=require("pg");
const games=require("./game-engines");

const app=express();
const port=Number(process.env.PORT||3000);
const pool=new Pool({connectionString:process.env.DATABASE_URL,max:10,idleTimeoutMillis:30000,connectionTimeoutMillis:8000,keepAlive:true});
pool.on("error",e=>console.error("postgres",e.message));
const token=process.env.DISCORD_BOT_TOKEN,guildId=process.env.DISCORD_GUILD_ID;
if(!token||!guildId){console.error("Missing Discord configuration");process.exit(1)}
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildPresences,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]});
app.set("trust proxy",1);app.disable("x-powered-by");
app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false}));
app.use(compression());app.use(express.json({limit:"256kb"}));
app.use(session({name:"mld.sid",secret:process.env.SESSION_SECRET,resave:false,saveUninitialized:false,store:new pgSession({pool,tableName:"user_sessions",createTableIfMissing:true}),cookie:{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:2592000000}}));
app.use(express.static(path.join(__dirname,"public"),{etag:true,maxAge:"5m"}));

const roleIds=new Set(["1530712642384040027","1521187079336362024","1531109479264026706","1548732297669255259","1548732341185155103","1548732606508703744"]);
let guildCache=null,memberCache=null,memberAt=0;
async function guild(){if(guildCache)return guildCache;guildCache=await client.guilds.fetch(guildId);return guildCache}
async function members(){if(memberCache&&Date.now()-memberAt<30000)return memberCache;const g=await guild();memberCache=[...(await g.members.fetch()).values()];memberAt=Date.now();return memberCache}
function me(req){return req.session.user||null}
function auth(req,res,next){if(!me(req))return res.status(401).json({error:"تسجيل الدخول مطلوب"});next()}
function owner(req,res,next){const u=me(req);if(!u||!["owner","admin"].includes(u.role))return res.status(403).json({error:"ليس لديك صلاحية"});next()}
function memberJson(m){const rs=m.roles.cache.filter(r=>r.id!==m.guild.id).sort((a,b)=>b.position-a.position).map(r=>({id:r.id,name:r.name,color:r.hexColor,position:r.position,mentionable:r.mentionable}));const lead=rs.filter(r=>roleIds.has(r.id));return{id:m.id,name:m.displayName,username:m.user.username,globalName:m.user.globalName,bot:m.user.bot,avatar:m.user.displayAvatarURL({extension:"png",size:256}),joinedAt:m.joinedAt,roles:rs,importantRoles:lead,rank:lead[0]?.name||rs[0]?.name||"عضو"}}
async function init(){await pool.query(`
CREATE TABLE IF NOT EXISTS app_users(id SERIAL PRIMARY KEY,username VARCHAR(32) UNIQUE NOT NULL,password_hash TEXT NOT NULL,discord_username VARCHAR(100) NOT NULL,discord_user_id VARCHAR(32),role VARCHAR(20) NOT NULL DEFAULT 'user',banned BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_login_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS site_stats(id INTEGER PRIMARY KEY DEFAULT 1,visits BIGINT NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS site_settings(key VARCHAR(80) PRIMARY KEY,value TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS game_sessions(id BIGSERIAL PRIMARY KEY,code VARCHAR(8) UNIQUE NOT NULL,game_id VARCHAR(60) NOT NULL,game_name VARCHAR(120) NOT NULL,owner_username VARCHAR(32) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'open',max_players INTEGER NOT NULL DEFAULT 4,players INTEGER NOT NULL DEFAULT 0,spectators INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),started_at TIMESTAMPTZ,ended_at TIMESTAMPTZ,players_json JSONB NOT NULL DEFAULT '[]'::jsonb,spectators_json JSONB NOT NULL DEFAULT '[]'::jsonb,state JSONB);
CREATE TABLE IF NOT EXISTS public_chat(id BIGSERIAL PRIMARY KEY,username VARCHAR(32) NOT NULL,discord_username VARCHAR(100),body VARCHAR(2000) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
INSERT INTO site_stats(id,visits) VALUES(1,0) ON CONFLICT DO NOTHING;
`)}
function code(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function gameUser(req,body){const u=me(req);return{username:String(u?.username||body?.username||"زائر"),discordUsername:String(u?.discordUsername||body?.discordUsername||"")}}
function pub(s){return{id:s.id,code:s.code,gameId:s.game_id,gameName:s.game_name,ownerUsername:s.owner_username,status:s.status,maxPlayers:s.max_players,players:Array.isArray(s.players_json)?s.players_json:[],spectators:Array.isArray(s.spectators_json)?s.spectators_json:[],createdAt:s.created_at,startedAt:s.started_at,endedAt:s.ended_at}}
app.get("/health",(req,res)=>res.json({ok:true,service:"mld",botReady:client.isReady()}));
app.get("/ready",(req,res)=>res.status(client.isReady()?200:503).json({ok:client.isReady()}));
app.get("/api/public/server",async(req,res)=>{try{const g=await guild();res.json({id:g.id,name:g.name,icon:g.iconURL({extension:"png",size:256}),memberCount:g.memberCount,ownerName:g.ownerId||"",invite:process.env.DISCORD_INVITE_URL||""})}catch(e){res.status(503).json({error:"Discord غير متاح"})}});
app.get("/api/members",async(req,res)=>{try{res.json({members:(await members()).map(memberJson)})}catch(e){res.status(503).json({error:"تعذر تحميل الأعضاء"})}});
app.get("/api/roles",async(req,res)=>{try{const g=await guild();res.json({roles:[...g.roles.cache.values()].filter(r=>r.id!==g.id).sort((a,b)=>b.position-a.position).map(r=>({id:r.id,name:r.name,color:r.hexColor,position:r.position,membersCount:r.members.size,mentionable:r.mentionable}))})}catch(e){res.status(503).json({error:"تعذر تحميل الرتب"})}});
app.get("/api/public/roles",async(req,res)=>{try{const g=await guild();res.json({roles:[...g.roles.cache.values()].filter(r=>r.id!==g.id).sort((a,b)=>b.position-a.position).map(r=>({id:r.id,name:r.name,color:r.hexColor,position:r.position,membersCount:r.members.size,mentionable:r.mentionable}))})}catch(e){res.status(503).json({error:"تعذر تحميل الرتب"})}});app.get("/api/top",async(req,res)=>{try{const a=(await members()).filter(m=>!m.user.bot).sort((x,y)=>{const xr=x.roles.cache.filter(r=>roleIds.has(r.id)).sort((a,b)=>b.position-a.position).first()?.position||0;const yr=y.roles.cache.filter(r=>roleIds.has(r.id)).sort((a,b)=>b.position-a.position).first()?.position||0;return yr-xr}).map(memberJson);res.json({members:a})}catch(e){res.status(503).json({error:"تعذر تحميل TOP"})}});
app.get("/api/site/stats",async(req,res)=>{try{const s=await pool.query("SELECT visits FROM site_stats WHERE id=1");const g=await guild();const ms=await members();const online=ms.filter(m=>!m.user.bot&&m.presence&&m.presence.status&&m.presence.status!=="offline").length;res.set("Cache-Control","no-store");res.json({visits:Number(s.rows[0]?.visits||0),memberCount:g.memberCount||ms.length,online,updatedAt:new Date().toISOString()})}catch(e){res.status(503).json({error:"stats_unavailable"})}});
app.post("/api/site/visit",async(req,res)=>{try{await pool.query("UPDATE site_stats SET visits=visits+1,updated_at=NOW() WHERE id=1");res.json({ok:true})}catch(e){res.status(500).json({error:"stats"})}});
app.get("/api/auth/me",(req,res)=>{const u=me(req);res.json({authenticated:Boolean(u),user:u})});
app.post("/api/auth/login",async(req,res)=>{try{const username=String(req.body?.username||"").trim().toLowerCase(),password=String(req.body?.password||"");const q=await pool.query("SELECT * FROM app_users WHERE username=$1",[username]);if(!q.rowCount)return res.status(401).json({error:"بيانات الدخول غير صحيحة"});const r=q.rows[0];if(r.banned)return res.status(403).json({error:"الحساب محظور"});if(!await bcrypt.compare(password,r.password_hash))return res.status(401).json({error:"بيانات الدخول غير صحيحة"});req.session.user={username:r.username,discordUsername:r.discord_username,discordUserId:r.discord_user_id,role:r.role};res.json({ok:true,user:req.session.user})}catch(e){res.status(500).json({error:"تعذر تسجيل الدخول"})}});
app.post("/api/auth/logout",(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get("/api/chat/messages",async(req,res)=>{const q=await pool.query("SELECT id,username,discord_username,body,created_at FROM public_chat ORDER BY id DESC LIMIT 100");res.json({messages:q.rows.reverse()})});
app.post("/api/chat/messages",auth,async(req,res)=>{const body=String(req.body?.body||"").trim();if(!body||body.length>2000)return res.status(400).json({error:"رسالة غير صالحة"});const u=me(req);const q=await pool.query("INSERT INTO public_chat(username,discord_username,body) VALUES($1,$2,$3) RETURNING *",[u.username,u.discordUsername,body]);res.json({ok:true,message:q.rows[0]})});
app.get("/api/games/sessions",async(req,res)=>{const q=await pool.query("SELECT * FROM game_sessions WHERE status IN ('open','playing') ORDER BY id DESC LIMIT 100");res.json({sessions:q.rows.map(pub)})});
app.post("/api/games/sessions",auth,async(req,res)=>{try{const id=String(req.body?.gameId||"").toUpperCase(),name=String(req.body?.gameName||id),max=Math.max(2,Math.min(8,Number(req.body?.maxPlayers)||4)),u=me(req),players=[gameUser(req,req.body||{})];let c=code();for(let i=0;i<5;i++){if(!(await pool.query("SELECT 1 FROM game_sessions WHERE code=$1",[c])).rowCount)break;c=code()}const q=await pool.query("INSERT INTO game_sessions(code,game_id,game_name,owner_username,max_players,players,players_json) VALUES($1,$2,$3,$4,$5,1,$6::jsonb) RETURNING *",[c,id,name,u.username,max,JSON.stringify(players)]);res.json({ok:true,session:pub(q.rows[0]),message:"تم إنشاء الجلسة "+c})}catch(e){res.status(500).json({error:"تعذر إنشاء الجلسة"})}});
app.post("/api/games/sessions/:code/join",auth,async(req,res)=>{const db=await pool.connect();try{await db.query("BEGIN");const q=await db.query("SELECT * FROM game_sessions WHERE code=$1 AND status='open' FOR UPDATE",[String(req.params.code).toUpperCase()]);if(!q.rowCount)throw Error("الجلسة غير موجودة أو بدأت");const s=q.rows[0],p=Array.isArray(s.players_json)?s.players_json:[],u=gameUser(req,req.body||{});if(p.some(x=>x.username===u.username)){await db.query("COMMIT");return res.json({ok:true,session:pub(s)})}if(p.length>=s.max_players)throw Error("الجلسة مكتملة");p.push(u);const x=await db.query("UPDATE game_sessions SET players=$2,players_json=$3::jsonb WHERE code=$1 RETURNING *",[s.code,p.length,JSON.stringify(p)]);await db.query("COMMIT");res.json({ok:true,session:pub(x.rows[0])})}catch(e){await db.query("ROLLBACK");res.status(400).json({error:e.message})}finally{db.release()}});
app.post("/api/games/sessions/:code/spectate",async(req,res)=>{try{const q=await pool.query("SELECT * FROM game_sessions WHERE code=$1 AND status='playing'",[String(req.params.code).toUpperCase()]);if(!q.rowCount)return res.status(404).json({error:"الجلسة غير متاحة"});const s=q.rows[0],a=Array.isArray(s.spectators_json)?s.spectators_json:[],u=gameUser(req,req.body||{});if(!a.some(x=>x.username===u.username))a.push(u);const x=await pool.query("UPDATE game_sessions SET spectators=$2,spectators_json=$3::jsonb WHERE code=$1 RETURNING *",[s.code,a.length,JSON.stringify(a)]);res.json({ok:true,session:pub(x.rows[0])})}catch(e){res.status(500).json({error:"تعذر تسجيل المشاهدة"})}});
app.post("/api/games/sessions/:code/start",auth,async(req,res)=>{try{const q=await pool.query("SELECT * FROM game_sessions WHERE code=$1 AND status='open'",[String(req.params.code).toUpperCase()]);if(!q.rowCount)return res.status(404).json({error:"الجلسة غير موجودة"});const s=q.rows[0],u=me(req);if(u.username!==s.owner_username)return res.status(403).json({error:"صاحب الجلسة فقط"});const p=Array.isArray(s.players_json)?s.players_json:[],engine=s.game_id.toUpperCase();if(!games[engine])return res.status(400).json({error:"اللعبة غير مدعومة"});const state=games.create(engine,p);const x=await pool.query("UPDATE game_sessions SET status='playing',started_at=NOW(),state=$2::jsonb WHERE code=$1 RETURNING *",[s.code,JSON.stringify(state)]);res.json({ok:true,session:pub(x.rows[0])})}catch(e){res.status(400).json({error:e.message||"تعذر بدء اللعبة"})}});
app.get("/api/games/sessions/:code/state",async(req,res)=>{try{const q=await pool.query("SELECT * FROM game_sessions WHERE code=$1 AND status IN ('open','playing')",[String(req.params.code).toUpperCase()]);if(!q.rowCount)return res.status(404).json({error:"الجلسة غير موجودة"});const s=q.rows[0];res.set("Cache-Control","no-store");res.json({ok:true,session:pub(s),state:s.state?games.pub(s.state,Array.isArray(s.players_json)?s.players_json:[],gameUser(req,req.query||{})):null})}catch(e){res.status(500).json({error:"تعذر تحميل حالة اللعبة"})}});
app.post("/api/games/sessions/:code/action",auth,async(req,res)=>{const db=await pool.connect();try{await db.query("BEGIN");const q=await db.query("SELECT * FROM game_sessions WHERE code=$1 AND status='playing' FOR UPDATE",[String(req.params.code).toUpperCase()]);if(!q.rowCount)throw Error("الجلسة غير موجودة");const s=q.rows[0],p=Array.isArray(s.players_json)?s.players_json:[],u=gameUser(req,req.body||{}),state=JSON.parse(JSON.stringify(s.state));const next=games.apply(state,state,p,u,req.body.action,req.body.data||{});const status=next.phase==="finished"?"ended":"playing";const x=await db.query("UPDATE game_sessions SET state=$2::jsonb,status=$3,ended_at=CASE WHEN $3='ended' THEN NOW() ELSE ended_at END WHERE code=$1 RETURNING *",[s.code,JSON.stringify(next),status]);await db.query("COMMIT");res.json({ok:true,finished:status==="ended",session:pub(x.rows[0]),state:games.pub(next,p,u)})}catch(e){await db.query("ROLLBACK");res.status(400).json({error:e.message||"الحركة غير صالحة"})}finally{db.release()}});
app.post("/api/games/sessions/:code/end",auth,async(req,res)=>{const q=await pool.query("SELECT * FROM game_sessions WHERE code=$1",[String(req.params.code).toUpperCase()]);if(!q.rowCount)return res.status(404).json({error:"الجلسة غير موجودة"});if(q.rows[0].owner_username!==me(req).username)return res.status(403).json({error:"صاحب الجلسة فقط"});const x=await pool.query("UPDATE game_sessions SET status='ended',ended_at=NOW() WHERE code=$1 RETURNING *",[q.rows[0].code]);res.json({ok:true,session:pub(x.rows[0])})});
app.use((req,res,next)=>req.path.startsWith("/api/")?res.status(404).json({error:"المسار غير موجود"}):next());
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
(async()=>{try{await init();await client.login(token);client.once("ready",()=>console.log("MLD Discord ready:",client.user.tag));app.listen(port,()=>console.log("MLD rebuilt server listening on",port))}catch(e){console.error("BOOT FAILED",e);process.exit(1)}})();
