import { test, expect } from "@playwright/test";
const BASE=process.env.BASE_URL||"https://discord-community-platform-production-9348.up.railway.app";
const routes=["members","top","roles","chat","private-chat","profile","message","games","groups","account","tickets","apply","reviews"];
test.describe("MLD public UI",()=>{
  test("homepage loads without console errors",async({page})=>{const errors=[];page.on("pageerror",e=>errors.push(e.message));await page.goto(BASE,{waitUntil:"networkidle"});await expect(page.locator("#top")).toBeVisible();expect(errors).toEqual([]);});
  for(const route of routes){test("route "+route+" renders",async({page})=>{const errors=[];page.on("pageerror",e=>errors.push(e.message));await page.goto(BASE,{waitUntil:"domcontentloaded"});await page.locator('[data-view="'+route+'"]').first().click();await expect(page.locator("#view-title")).not.toHaveText("الصفحة الرئيسية",{timeout:5000});await expect(page.locator("#status")).not.toHaveText("تعذر فتح القائمة حاليًا");expect(errors).toEqual([]);});}
  test("games lobby is real and interactive",async({page})=>{await page.goto(BASE,{waitUntil:"networkidle"});await page.locator('[data-view="games"]').first().click();await expect(page.locator("#game-create")).toBeVisible();await expect(page.locator("#game-lobbies")).toBeVisible();await page.locator("#game-kind").selectOption("TRIVIA");await page.locator("#game-max").fill("2");});
  test("mobile menu rebuilds and routes",async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto(BASE,{waitUntil:"networkidle"});await page.locator("#menu").click();await expect(page.locator("#mobile-menu")).toHaveClass(/open/);await page.locator('#mobile-menu [data-view="games"]').click();await expect(page.locator("#game-create")).toBeVisible();});
});
test.describe("MLD public API",()=>{for(const path of ["/api/public/server","/api/public/roles","/api/public/members","/api/public/top","/api/games","/api/site/stats","/api/site/settings","/api/reviews"]){test(path+" returns JSON",async({request})=>{const r=await request.get(BASE+path);expect(r.status()).toBeLessThan(500);expect(r.headers()["content-type"]||"").toContain("application/json");});}});
